# RabbitMQ VM – single service
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_vol:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_vol:
